- tests_openssl.c
- utils.c
- wallet.c
This fixes some formatting warning / errors when building on Linux.
lucas@linux-pdex:~/Projekte/mcu> gcc --version
gcc (SUSE Linux) 4.7.2 20130108 [gcc-4_7-branch revision 195012]
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
lucas@linux-pdex:~/Projekte/mcu> uname -a
Linux linux-pdex.site 3.7.10-1.45-desktop #1 SMP PREEMPT Tue Dec 16 20:27:58 UTC 2014 (4c885a1) x86_64 x86_64 x86_64 GNU/Linux
> Building on Linux

- .travis.yml
- README.md
- random.c
- tests_openssl.c
- utils.c
- wallet.c
Builds on top of https://github.com/digitalbitbox/mcu/pull/1.
You'd need to go to https://travis-ci.org/ and activate it there. It's free.
Travis is used by Bitcoin Core, libsecp256k1, libbitcoin and many other projects.
Currently only Linux is on by default. We'd have to ask the support to activate OS X (I don't know the requirements, but we had also OS X in Open Transactions).
It runs tests_unit  and tests_openssl 200, but tests_openssl currently always returns 0 / success.
The change in random.c is needed because Travis still runs on Ubuntu 12.04 with GCC 4.6. If you want a higher version of GCC you could install it via the .travis.yml file, but that makes the build a lot slower.
> Add Travis CI

- .travis.yml
- README.md
The build will fail if the coding style is not
> astyle --style=stroustrup --indent-switches --indent-labels --pad-oper --pad-header --align-pointer=name --add-brackets --convert-tabs --max-code-length=90 --break-after-logical --suffix=none *.c *.h --dry-run -Q
Travis will list the file with the problem (example: https://travis-ci.org/lclc/mcu/jobs/67420821)
> Travis astyle

- CMakeLists.txt
- src/aes.c
- src/base58.c
- src/bip32.c
- src/commander.c
- src/memory.c
- src/sha2.c
- src/utils.c
- tests/CMakeLists.txt
- tests/tests_unit.c
I've deactivated -Wcast-qual in the tests folder for now (it triggered a lot of warnings in the  trezor code).
> -Wwrite-strings, -Wcast-qual, -Wmissing-prototypes

- README.md
- contrib/git/pre-commit
This way you don't have to wait for Travis to know about coding style issues.
Has to be activated manually on client side (as described in README.md).
> Git: Add astyle commit hook

- tests/utest.h
Got an error when I tried to use utest.h in the bitbox-client library because of those missing includes (here included by tests_unit.c).
> utest: Add stdio.h and string.h includes

- tests/tests_api.c
Doesn't get catch by Travis because it's in the #ifndef CONTINUOUS_INTEGRATION part.
> test_api: Fix cast-qual in HID tests

- CMakeLists.txt
- README.md
While building i stepped over this.
Maybe it would be worth to add https://github.com/signal11/hidapi as submodule and somehow included in the the CMake process?
> fix osx linker flags for libhidapi, mention it in README.md

- tests/tests_api.c
The hidapi library in linux reads 64 bytes at a time instead of the full `HID_REPORT_SIZE` buffer as is done on OS X. This fix works with both operating systems (tested on Ubuntu 14.04 and OS X 10.10.3).
> fix api_hid_read for linux (tested with Ubuntu 14.04)

- src/sd.c
Currently, files that are to be erased on the micro SD card are unlinked (f_unlink). The data remains and could be recovered. This update will wipe file contents before f_unlink is performed, and also return error messages if something goes wrong.
> overwrite (secure erase) files before f_unlink in 'erase' command

- src/random.c
- src/sd.c
To remove some of the trust required for the ATAES hardware random number generator, one can add entropy from an independent source using bitwise xor ([proof](http://crypto.stackexchange.com/questions/17658/mixing-entropy-sources-by-xor)). 
In this update, the random number returned by the hardware RNG is xor'd with a double SHA hash of random parts of the machine code, as gathered [here](https://github.com/dbitbox/mcu/blob/master/src/memory.c#L236-L258).
> Independent entropy to RNG

- src/commander.c
- src/commander.h
- src/flags.h
- src/memory.c
- src/memory.h
To avoid a novice user from forgetting to create a backup, require its creation for the `seed: create` command. This requires a micro SD card to be present.
The alternative 2 methods of seeding from an existing micro SD backup file or as input via the USB are not affected.
One question: should the automatic backup be encrypted or not? It is encrypted in this pull request, with the AES encryption key being the same as used to send commands to the device via the USB interface.
> Autobackup on seed

- src/commander.c
`xpub` command to get public keys. An empty string should get treated as an error. Simple one line commit, so I will just merge it right away.
> return on invalid input (empty string)

- CMakeLists.txt
- src/commander.h
Automatically use the Git version string + hash as the dbb version string. Example output:
```
$ bin/tests_cmdline '{"device":"version"}'
utils send:   {"password":"standard_password"}
utils recv:   { "password": "success" }
utils send:   {"device":"version"}
utils recv:   /* ciphertext */ { "version": "1.0.0 (ab96b299c7d07e65d77e0262f09bf2a33f44eb4f)" }
```
(This commit also makes the default compilation not verbose.)
> use git version tag as dbb version

- src/sd.c
- tests/tests_api.c
Simple update after doing live testing:
- Overwriting files on microSD needs FA_CREATE_ALWAYS flag instead of 	FA_OPEN_EXISTNG.
- `tests_api.c` corrected checks - no longer have an error when overwrite verification key on SD card; different devices may have different version strings, so don't check for an exact version match.
> fixes from live testing

- CMakeLists.txt
- src/commander.c
- src/commander.h
- src/version.h
- src/version.h.in
- tests/tests_api.c
Pull version values from latest tag on git using `git describe --tags` instead of hardcoded in cmake file. The version string will look like:
```
$ git describe --tags
v1.0.2-6-g11762df
```
Put the version into a file instead of a makefile `-D` compilation flag.
(Also removed commented line in `tests_api.c`)
> pull version numbers from latest git tag; use version files

- src/commander.c
- src/version.h
Signing verification process is currently to send sign command twice. First returns an encrypted 'echo' used for 2FA verification. The second will process the command if the touch button is held. This pull request restarts this process if a different command is input before the second sign command.
> restart signing verification process if non-sign command is entered

- CMakeLists.txt
First commit reactivates the git submodule initialization (EDIT: so users don't have to do anything manually other than cmake .. && make).
Second one sets the version.h file to .gitignore, since it gets generate everytime someone builds the file and is outdated everytime one makes a new commit.
> Fix cmake submodule

- src/memory.c
random.h is not used in memory.c
Also, would it make sense to replace the /dev/urandom in random.c with rand() ?
So the source code would compile on Windows too (or more likely, I didn't try it).
I'm not sure, but I think rand() has worse entropy than /dev/urandom, but it's only used for testing.
> Memory.c: Replace random.h include with stdlib

- src/commander.c
- src/flags.h
- tests/tests_api.c
For an `xpub` command, return the xpub in plaintext as before and additionally return the same xpub encrypted with the verification password. The smartphone app can be used to decode the encrypted xpub in order to verify the receiving address has not been tampered by MITM.
A reply now looks like:
```
{
"xpub": "xpub6AxQMCbHigHGo8mzY7XMVa7StmKjzoemCHB13uGZrwgb5WsBtCJCyVjSMcMM32m9QvSy4SFYWuxTnLKiZz48AteEEHG6hAMQ996Y1jjvArL" ,
"echo": "5afwOMNDqeR02X+xDVhfQIViJUOboC+wx/orDEEG7Jmhouui2epYiLGpS76YyZ5F4l08qYRQg0f5Gn00lODdAiCUkbfwwFY3iBC9I+MpsAehx5toiM6vXHbjP6nkupdrjPFwsquguQ0TiHAFMZisgtRGo8znmZZCYeitzMeDULk="
}
```
> add encrypted xpub to allow 2FA of receiving addresses

- src/memory.c
- src/memory.h
- src/sham.c
- src/sham.h
- src/touch.c
- src/touch.h
Touch button parameters are hardcoded, and so memory management is not needed.
In early versions, touch button settings (timeout and threshold) could be changed through the API and were stored in secure EEROM. Later, this was removed from the API for security reasons: setting a low threshold could turn off the touch button and allow remote signing without user knowledge.
> remove touch button parameters from eeprom memory

- src/commander.c
- src/flags.h
- src/wallet.c
- tests/tests_api.c
- Only allow digits for keypath indices.
- Require the first two keypath values to be `m/`.
- As before, allow `p`, `h`, `H`, or `` ` `` to indicate hardened derivation.
An offline suggestion was to also check the integer range for indices, but I think the code is safe as is. Indices are stored in uint32_t variables, and sscanf would take the modulus of a larger number.
> add sanity checks for keypath

- src/commander.c
- src/flags.h
- src/memory.c
- src/memory.h
- src/version.h
- src/wallet.c
- src/wallet.h
- tests/tests_unit.c
Extended private keys (xpriv) are the most general representation of a BIP32 master seed. On the other hand, a mnemonic seed is specific to a given language (the BIP39 English wordlist is used here, but other wordlists exist), is not recoverable from the xpriv (due to being hashed), and is not fully accepted (e.g. Electrum uses a different mnemonic-to-seed derivation function). 
A mnemonic is an easy way for a user to copy a seed by hand, but copying by hand is not necessary with the DBB. Note that the xpriv uses base58check encoding.
**Changes**
- The `backup` command always save the xpriv to the microSD card. 
- The `seed` command accepts an xpriv source, via either the microSD card or input by USB. (A BIP39 english mnemonic seed can still be input by microSD card or USB, as before.) …
> use xpriv instead of mnemonic as backup to micro SD

- src/commander.c
- src/commander.h
- src/flags.h
User feedback indicated increasing the number of access attempts before auto-erase is desired such that there is a bit less stress in the case the password cannot be recalled. Was 5, now 15, so brute force is still prevented.
> increase password attempts before auto erase

- src/commander.c
- src/commander.h
- src/flags.h
- src/memory.c
- src/sham.c
- src/wallet.c
- tests/tests_api.c
- tests/tests_cmdline.c
Fixes #55.
Fixes #56.
**New command**
```
{device: info}
```
**Response**
```
{
"serial": "01010101000000000000000000000000" , 
"version": "v1.1-7-g5fffa2a" , 
"xpub":"xpub661MyMwAqRbcFuuEM2tgZEGAVdUSB4A43rmq5GCPh7bZMoA2aGWwsFiEUbT2aN1rUV6RrDbnjSKFxQrss7hQfnTKG3TyeuisYeQaJPQwDto" , 
"lock": false , 
"name": "Digital Bitbox" 
}
```
> add device:info command

- CMakeLists.txt
- src/CMakeLists.txt
- src/bip32.c
- src/commander.c
- src/ecc.c
- src/ecc.h
- src/secp256k1.c
- src/uECC.c
- src/uECC.h
- src/utils.c
- src/version.h
- src/wallet.c
- tests/CMakeLists.txt
- tests/tests_api.c
- tests/tests_openssl.c
- tests/tests_secp256k1.c
- tests/tests_unit.c
Use [bitcoin/secp256k1 ECC library](https://github.com/bitcoin/secp256k1) because it is well reviewed, does signing 6x faster, supports ECDHA and Schnorr which may be useful in future, and is made with sufficient paranoia. The drawback is it is big, about 92kB larger than the current 'micro' uECC library, and the MCU flash space is nearly full. In case space is needed in the future, a flag `ECC_USE_SECP256K1_LIB` allows selecting secp256k1 (default) or uECC.
Notes:
- Unit tests included with secp256k1 are activated in Travis CI.
- The secp256k1 library requires the second half of the signature to use the 'lower-S form', i.e.  the lower half of the range from 0x1 to 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0, inclusive. Therefore, unit tests for signatures in …
> switch to bitcoin/secp256k1 ecc library

- .travis.yml
- src/commander.c
- src/flags.h
- src/sham.c
- src/sham.h
- src/touch.c
- src/touch.h
- src/version.h
Use 'long touch' option for all commands requiring touch: `sign`, `seed`, `erase`, and `password`. 
This simplifies the user experience by having to know only one touch button protocol. It also prevents accidentally accepting a `seed` command, by bumping the dbb for example. New `seed` commands erase the old seed, which is a potential risk to lose funds.
Long touch was used for `sign` before: pressing the touch button for more than 3 seconds equals 'accept' while pressing for less than 3 seconds equals 'reject'. The alternative 'short touch' option is no longer used: a single touch equals 'accept' with a timeout after 3 seconds. (I think it is good to keep the short touch code for potential future dev.) Previously, `erase` required 3 short touches in a row.
> Use 'long touch' option

- src/commander.c
- src/memory.c
- src/memory.h
- src/random.c
PR #67 produced an infinite loop: `random_bytes` called a function to read the 'stand' aes key from eeprom, which created an infinite loop by calling `random_bytes`.
This is fixed by loading the aes keys stored in eeprom into RAM before a command is processed (keys are erased from memory after a command is processed) and creating a new function `memory_report_aeskey(id)` that reads keys from RAM.
Minor changes:
- Some code only run on chip (i.e. `#ifndef TESTING`) is now run off chip too to improve testing. 
- Gave shorter names to some variables and functions.
> bugfix extra random entropy

- src/ecc.c
Closes #73.
Passed testing onchip. However it required a change in the secp256k1 library: https://github.com/digitalbitbox/secp256k1/commit/52bc47defdf1ae96419034bc9fbd38183f5e3705
likely due to the target ARM architecture: http://stackoverflow.com/a/13284139
> use secp256k1_context_randomize() for secp library context init

- .travis.yml
- firmware.cmake
- src/ecc.c
Expand travis testing using a matrix of environment variables, including a build of the firmware.
( To be rebased on top of #78 )
> expand travis testing

- .travis.yml
- README.md
- src/CMakeLists.txt
- src/flags.c
- src/flags.h
fixes #82 
The external yajl and secp256k1 git submodules are excluded from coverage.
> add coveralls test coverage

- src/commander.c
- src/wallet.c
- src/wallet.h
- tests/tests_api.c
- tests/tests_unit.c
Since backups are now an `xpriv` key instead of a `mnemonic`, on chip seed creation can bypass mnemonic generation. In other words:
```
random32 -> mnemonic -> seed64
```
can instead be
```
random64 -> seed64
```
Side benefits are double the entropy and faster seed creation.
> bypass mnemonic generation for seed:create

- src/commander.c
- src/commander.h
- src/flags.h
- src/led.c
- src/sham.c
- src/touch.c
- tests/tests_api.c
- tests/tests_unit.c
- tests/utest.h
1
Updates the touch sequence used for #68 (ECDH 2FA key pairing).
As before, the LED blinks 1, 2, 3, or 4 times. But now, the next set of blinks does not occur until after the user 'short' touches the touch button. This allows time for the user to enter the number of blinks into the 2FA device. The procedure can be repeated any number of times, and must occur at least one time. A 'long' touch exits the procedure. 
---
2
Adds unit tests.
---
3
API now returns sample encrypted text to verify that pairing was done correctly:
**send** (enter the shared public key from the 2FA device)
```
{ "verifypass": { 
"ecdh": "028d3bce812ac027fdea0e4ad98b2549a90bb9aa996396eec6bb1a8ed56e6976b8"
}
}
```
**reply** (returns the shared public key from DBB)
```
{"verifypass": {
"ecdh": …
```
> updates for ecdh 2FA pairing

- src/commander.c
- src/flags.h
- src/wallet.c
- src/wallet.h
- tests/tests_api.c
Simplify the signing protocol by using only one sign `type` previously called `type: meta`. `type: hash` was redundant, and `type: transaction` doesn't work for multisig, which is default for the dbb-app.
> remove hash and tx sign types

- src/ecc.c
- src/led.c
- src/secp256k1.c
- src/uECC.c
- tests/tests_secp256k1.c
The smartphone 2FA app uses javascript Crypto.js library, which unfortunately does not produce the same ECDH shared secret as uECC or libsecp256k1. The Crypto.js shared secret is an unhashed point x coordinate. uECC and libsecp256k1 give single sha256 hash of the compressed pubkey (i.e. x coordinate with an extra 0x02 or 0x03 byte prefixed). Therefore, this pull request removes the sha256 hash and code calling ECDH (ecc.c) removes the byte to get ECDH working with the smartphone.
(Also up to date with current secp256k1.)
> ECDH updates

- src/commander.c
- src/flags.h
- src/led.c
- src/sham.c
- src/touch.c
Don't require user touch to continue to next blink sequence. A short touch in between blink sequences exits.
> update blink UI

- src/commander.c
- src/flags.h
- src/sd.c
- src/sd.h
- src/sham.c
- src/sham.h
- tests/tests_api.c
The extra field returned is:
```
"sdcard": true
```
or
```
"sdcard": false
```
> indicate presence of sd card for device:info command

- src/memory.c
…instead of arbitrary selections. Just one byte changed (at any location) will make a new mempass obfuscation key.
> use hashes to create mempass aes key

- src/commander.c
- src/flags.h
- src/wallet.c
- src/wallet.h
- tests/tests_api.c
Fixes #103.
(Reference #43.)
Use a compressed pubkey instead of the address when checking if a pubkey is part of the wallet (e.g. for verifying output change addresses in transactions).
**send to dbb**
```
{ 
"sign": 
{
"meta": "<<meta data here>>", 
"data": [
{"hash":"c6fa4c236f59020ec8ffde22f85a78e7f256e94cd975eb5199a4a5cc73e26e4a", "keypath":"m/44p"},
{"hash":"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", "keypath":"m/44p"}
], 
"checkpub":[
{"pubkey":"000000000000000000000000000000000000000000000000000000000000000000", "keypath":"m/44p/0p/0p/1/8"},
{"pubkey":"032ab901fe42a05e970e6d5c701b4d7a6db33b0fa7daaaa709ebe755daf9dfe0ec", "keypath":"m/44p/0p/0p/1/8"}
]
}
}
```
**echo reply**
```
{ 
"sign": 
{
"meta": "<<meta data here>>", 
"data": [
{ …
```
> signing checkpub: use pubkey instead of address

- src/memory.c
This way, the password and master seed (things in ataes eeprom memory) remain accessible after a firmware update. Mempass, which is derived by a hash of the bootloader bytes, will be unique for each device by padding the bootloader with random bytes before loading it to the device.
> mempass derived only from bootloader bytes

- src/commander.c
- src/flags.h
- src/sham.c
- src/sham.h
- tests/tests_api.c
The new JSON field is `bootlock` with values of `true` for locked and `false` for unlocked bootloader.
Sending
```
{"device":"info"}
```
Returns
```
{ 
"device": {
"serial": "00313453434d59593133303033303434", 
"version": "v1.2.0-104-gb609385", 
"name": "Digital Bitbox", 
"id": "694383184e6e598debd221ec4f886424b9f78daf8b3e1cd6adf24c8795249fce", 
"seeded": true, 
"lock": false, 
"bootlock": true, 
"sdcard": false
}
}
```
> return bootloader lock status with device:info command

- src/commander.c
- src/flags.h
- src/sd.c
- src/sd.h
- src/sham.c
- src/sham.h
- tests/tests_api.c
Currently, erase would erase all backup files.
To instead erase a single file: `{"backup": {"erase": "backup.bak"}}` 
As before, `{"backup": "erase"}` will erase all backup files.
> erase single file on sd card

- src/commander.c
- src/flags.h
- tests/tests_api.c
**send**
```
{
"backup": {
"check": "[filename]"
}
}
```
**reply**
```
{"backup": "success"}
```
If the backup does not match the wallet seed:
```
{ 
"error": {
"message": "Backup file does not match wallet.", 
"code": 410, 
"command": "backup"
}
}
```
> option to check if sd card backup file matches seeded wallet

- src/CMakeLists.txt
- src/commander.c
- src/memory.c
- src/memory.h
- src/pbkdf2.c
- src/pbkdf2.h
- tests/tests_unit.c
(does not affect dbb app or USB HID API in general)
Use pbkdf2-hmac-sha512 to stretch the user password for encrypting backups on the SD card.
> key stretch pw for encrypted sd card backup files

- src/commander.c
- src/drivers/common/services/usb/class/hid/device/generic/udi_hid_generic.c
- src/drivers/config/conf_usb.h
- src/flags.h
- src/memory.c
- src/memory.h
- src/usb.c
- src/usb.h
- src/utils.c
- tests/api.h
- tests/tests_api.c
This PR simplifies the code and adds security for the signing verification process. 
For both locked and unlocked devices, 2 sign commands are required (the recent PIN protocol update required 3 commands). Now, the second sign command no longer needs to be identical to the first because the first sign command is remembered. This guarantees that the verification 'echo' message displayed on a 2FA device will match the data to be signed. 
For locked devices, the second sign command must include the lock PIN. For unlocked devices, the second command can be any valid command and is silently ignored - sending an empty sign command `{"sign":""}` or similar is recommended for keeping client code readable. As before, touch button user confirmation begins on receipt of the second command, and the …
> overhaul signing verification

- src/commander.c
- src/drivers/thirdparty/qtouch/generic/include/touch_api.h
- src/flags.h
- src/touch.c
- src/touch.h
In order to visually distinguish touch button user confirmation for signing versus other commands, this PR blinks the LED for signing commands. The blink is 3 sec on and 0.3 sec off. 
For all 'long touch' user confirmations, a timeout of 30 sec is added.
> blink LED for signing command; 30 sec timeout for long touches

- src/bootloader.c
- src/bootloader.h
- src/flags.h
- src/startup.c
- src/uECC.c
Currently 2 of 3 but easy to update once secure keys are chosen.
Clients (i.e. dbb-app) operate as before and just concatenate signatures for the extra keys when sending the 's' command to the bootloader. Order is important. For example, if a signature for the second key is missing, a 'dummy' sig, such as 64 bytes of 0xFF, should be inserted before concatenating the signature for the third key, and so on.
> bootloader M of N signature verification of firmware

- src/commander.c
- src/flags.h
- tests/tests_api.c
May be convenient for possible future applications for testing if a second factor authentication device is paired. The test message can only be decrypted by a TFA device that was paired to the Digital Bitbox.
Send
```
{ "device":"info" }
```
Reply
```
{ 
"device": {
"TFA": "GbS++B3gUAtFRzKFkmg0RiUlFrzzZE5Kq6OlvJHfQfLPhbmrs/A0BeJBMF+UL4Jc",
"serial": "01010101010101010101010101010101", 
"version": "v1.2.0-155-g1225f47", 
"name": "Digital Bitbox", 
"id": "", 
"seeded": false, 
"lock": false, 
"bootlock": true, 
"sdcard": true
}
}
> device:info returns TFA test message

- src/commander.c
- src/commander.h
- src/drivers/config/conf_usb.h
- src/flags.h
- src/utils.c
- src/utils.h
- tests/tests_api.c
The motivation for this PR is to increase the number of transaction inputs that can be signed in one command. (If a transaction has more inputs, then it must be 'streamed' to the device.)
A transaction with ~~20~~ 18 inputs (`data`) can be signed at one time, assuming meta is a 64-character hash and one output pubkey is checked if present in the wallet (i.e. the change output). 
```
{
"sign": {
"meta": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", 
"checkpub": [
{ "pubkey": "000000000000000000000000000000000000000000000000000000000000000000", "keypath": "m/100203p/45p/0/100" }
], 
"data": [ 
{ "hash": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", "keypath": "m/100203p/45p/0/100" },
{ "hash": …
```
> double the usb buffer size to 4096 characters

- src/commander.c
- src/firmware.c
- src/memory.c
- src/memory.h
- tests/tests_api.c
Reads to the ataes chip are slow. This PR changes initialization reads of data in the ataes chip to occur when the device is plugged in instead of each time a command is received.
> speed up command processing

- src/bootloader.c
- src/bootloader.h
Useful during manufacturing - can automatically reboot into firmware after it is loaded.
> Reboot command for bootloader

- src/drivers/config/conf_usb.h
- src/firmware.c
The USB 'serial number' for a device is `dbb.fw:v1.3.0` as before. However, to identify a freshly erased device, the serial number (on plugin) for devices that do not have a password set is appended by `:0` to be `dbb.fw:v1.3.0:0`.
> dynamic serial number

- src/commander.c
- src/flags.h
- tests/tests_api.c
Example:
`{ "seed": {"source":"create", "filename":"filename.bak"} }"`
The PR is backward compatible: a command without a filename falls back to creating a backup with an automatically generated filename (maximum 50 now instead of 10 autobackup files). Sending a filename for older firmware is also ok as it will be silently ignored.
> option to set backup filename for seed source:create command

- src/commander.c
- src/flags.h
- tests/tests_api.c
Sending an unencrypted command `{"ping":""}` will return `{"pong":"false"}` or `{"pong":"password"}` depending if the password is set or not.
> unencrypted ping command to test if pw set

- .travis.yml
- CMakeLists.txt
Use the bitcoin/secp256k1 library for ecc signing.
The library is modified to decrease the precomputed table size by half to 32kB, in order to fit on the MCU, at the expense of running at 75% signing speed. (Ref PR: https://github.com/bitcoin/secp256k1/pull/337)
> use secp ecc lib by default, with smaller precomputed table for signing

- .gitignore
- README.md
- Vagrantfile
Just so it doesn't mess with the default build-path in the README.
Also, the currently build on my Arch gives some warning errors on libsecp256k1, maybe we should disable the cmake warnings for external libraries. Or fix it - if they want those changes upstream (might slow it down).
> Vagrant: Use a different directory name for the build

- .gitignore
- src/commander.c
- src/flags.h
- src/sd.c
- src/utils.c
- src/utils.h
- tests/tests_api.c
Limit backup filename characters to be:
```
.-_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
```
> limit backup filename characters

- src/flags.h
- src/sd.c
- tests/tests_api.c
Returns truncated list of files (newest files dropped). The buffer limit for the list of files is 2048 characters.
```
{ "warning": "Too many files to read. The list is truncated.", "backup": ["file1","file2","file3", ... ]}
```
Previously an empty list was returned with an error message.
> give warning when too many backup files to list

- src/commander.c
- src/flags.h
- src/memory.c
- tests/tests_api.c
Helps improve organizing wallets.
Backup looks like `<xpriv>-<name>`:
```
xprv9T4ue1W81ZrQH1NrG7c3qSMKYC2Rvu6LZNEAcfdJ443K33ZzZgdTVnzwmjEfy52tAcGq51eSG9s2K3oPWeCcfHzHdthnG3WjJAwtBS3akCG-My Digital Bitbox
```
> backups include device name concatenated to end of xpriv

- src/commander.c
- src/flags.h
- src/memory.c
- src/memory.h
- tests/tests_api.c
THIS BREAKS API 
(seed and backup commands)
Now requires encryption passphrase for backups always. This separates device password from backup password. A client is recommended to strengthen the passphrase before sending. Note that, as a failsafe against naive clients, the MCU will still key stretch, salt, and hash the input key, but only 2048 rounds of PBKDF2 due to limited MCU resources. 
The seed command is now:
```
"seed" : 
{
"source" : "source",
"key" : "passphrase",
"filename" : "filename"
}
```
Affected backup commands are now...
For creating a backup:
```
"backup" : 
{
"key" : "passphrase",
"filename" : "filename"
}
```
For checking if a backup file matches what is seeded in the wallet:
```
"backup" : 
{
"key" : "passphrase",
"check" : "filename"
}
```
The API BREAK is that `key` …
> Require encryption for backups, enter by api

- src/commander.c
- src/flags.h
- src/led.c
- src/led.h
- src/touch.c
To be called when the cancel button is pushed in the dbb-app smart verification dialogs.
> add led abort (quick flashes) command

- src/commander.c
- src/sd.c
- src/sd.h
- src/sham.c
- src/sham.h
- tests/tests_api.c
Motivation: can insert the SD card into a printer to print the encrypted backup on paper.
- NOT BACKWARD COMPATIBLE -
Old backups cannot be loaded - an error would be returned if it is tried. However, old backups already can not be loaded due to an update in the desktop app for the next release that corrects the BIP32 key paths -- i.e. old backups would load without error, but no coins would be found on the new key paths, giving a zero balance in the desktop app. Probably giving an error is better situation than showing a zero balance.
TODO
The desktop app should pass the backup file name using a .pdf extension.
Put recovery instructions on website. (Include client-side javascript to decrypt?)
> use pdf format for backups

- src/commander.c
- src/flags.h
- tests/tests_api.c
> return 'success' for led commands; rename command 'toggle' to 'blink'; add tests

- src/commander.c
- src/flags.h
- src/memory.c
- src/memory.h
- tests/api.h
- tests/tests_api.c
Motivation is to erase device if in a compromised situation.
To set: `{"set_reset_password":"password"}`
Then any command sent to the device that is encrypted with this password will reset/erase the device.
> add second password that resets device if used

- py/send_command.py
- src/commander.c
- src/memory.h
- src/u2f_device.c
- tests/tests_api.c
Required so that old devices upgrading their firmware will have U2F enabled by default.
> Feature set: set bit (1) to enable U2F instead of unsetting bit

- src/u2f_device.c
- src/u2f_device.h
- tests/api.h
... via u2f_hijack. 
The website origin is part of the hashed U2F client data to be matched by `U2F_HIJACK_CODE`. A beneficial consequence is that the u2f_hijack interface works for specified websites and will not work for fake or phishing websites.
> access to www.myetherwallet.com

- src/commander.c
- src/led.h
This improves the UX by avoiding user confusion on how to end the blink code pairing.
> set max limit to number of blink sets for mobile pairing

- src/commander.c
- src/flags.h
- src/memory.c
- src/memory.h
- src/random.c
- tests/api.h
- tests/tests_api.c
Allow using an ephemeral session key such that the client app does not need to store the device password for either the standard or hidden wallet. This also provides some backward privacy. The session key is optional, such that the PR is backward compatible with the existing desktop app that does not use a session key.
API
---
**command**
```{"session" : "set"}```
**reply**
```{"session" : "__password__"}```
The returned session password is random and in hexadecimal format. It is valid until the device is unplugged or if "set" again or turned "off" (see below). Access through the standard or hidden password is disabled while a session password is activated.
--
**command**
```{"session" : "off"}```
**reply**
```{"session" : "success"}```
Resumes access through the standard or hidden …
> Session key for AES-256-encrypted USB communication

- py/pad_boot_binary.py
- src/startup.c
#189 (adding SPI and TWI modes) caused the bootloader to be bigger than allocated 32kB. 
This should have been caught by Travis CI (fixed here). The bootloader used SPI/TWI to get a random number for the stack smashing guard variable. The random number can be instead taken from the factory-installed entropy bytes programmed in flash.
> shrink bootloader size

- .travis.yml
- .valgrind.supp
- src/CMakeLists.txt
- src/commander.c
- src/flags.h
- src/sd.c
- src/sham.c
- src/sham.h
- tests/CMakeLists.txt
- tests/api.h
- tests/tests_api.c
Simulating the SD card in unit tests (using FILE calls) allows more comprehensive testing of the backup function, including pdf creation and parsing.
> Simulate SD card in unit testing

- src/commander.c
- src/flags.h
- src/memory.c
- src/memory.h
- src/sd.c
- src/sd.h
- tests/api.h
- tests/sd_files/test_backup.pdf
- tests/sd_files/test_backup_hww.pdf
- tests/sd_files/test_backup_u2f.pdf
- tests/sd_files/test_backup_v2.2.3.pdf
- tests/tests_api.c
- tests/tests_u2f_standard.c
Rationale: The U2F master key is currently not backed up on the micro SD card. 
Goal: Allow back up and recovery of the U2F master key, and allow the possibility for it to be independent of the hardware wallet. The latter is because if one creates a new hardware wallet, one would likely not want to reset U2F because any previously paired websites will no longer be accessible.
Additional changes:
- The PDF file now saves the master seed (and u2f key) 2 extra times (within commented lines inside the PDF) for redundancy against bit corruption. The commented lines are viewable with a text editor.
- The wallet `name` is now limited to alphanumeric_hyphen_underscore_period characters. (This was already being enforced by the desktop client app.)
*command*
```
"backup" : 
"key" : "key", …
```
> U2F backup/load/reset

- src/sd.c
When the backup file can't be created in the host file system, the
test segfaults.
> tests: fix possible segfault in sd.c

- tests/tests_u2f_standard.c
- tests/u2f/u2f_util_t.c
- tests/u2f/u2f_util_t.h
Bugfix: The unit testing API calls for the standard HWW interface, used to update the U2F counter value, were being run in simulation only for both simulation and live testing.
> fix live device counter check in u2f unit tests

- src/commander.c
- tests/tests_api.c
Before, it would return an invalid json `{"sign":}`.
Also, the data checks are now consistent in echo/sign.
> sign: error on empty data

- src/bootloader.c
- src/commander.c
- src/memory.c
- src/u2f_device.c
- src/utils.h
- src/wallet.c
- tests/tests_api.c
append `;` to `ASSERT_SUCCESS`
use `MEMEQ` instead of `memcmp()==0`
> refactoring for better readability

- src/CMakeLists.txt
- src/aescbcb64.c
- src/aescbcb64.h
- src/commander.c
- src/commander.h
- src/ecdh.c
- src/ecdh.h
- src/flags.h
- src/flash.c
- src/flash.h
- src/led.c
- src/memory.c
- src/memory.h
- src/sharedsecret.c
- src/sharedsecret.h
- src/utils.c
- src/utils.h
- tests/api.h
- tests/hmac_check.h
- tests/tests_api.c
- tests/tests_unit.c
Update pairing between device and mobile app and use an hmac. The ECDH code is removed from `commander.c` and put into `ecdh.c`. The led abort command was deprecated while the led blink command was modified to blink 5 times quickly.
> Update pairing mechanism and add MAC

- tests/tests_api.c
Non-live testing mode uses a simulated SD file storage, copies known backup files there and loads them. 
Live testing mode was trying to load such a file but of course the onboard SD card is not the computer's local file system.
> tests_api minor fix

- src/commander.c
- tests/tests_api.c
The plaintext ping response now includes the firmware version, same
format as in the response of the device info command.
Useful if one does not have access to the usb descriptor, e.g. when
communication using u2f.
> return firmware version in ping

- src/commander.c
- src/flags.h
- src/flash.c
- src/sd.c
- src/sd.h
- src/simulator.c
- src/wallet.c
- src/wallet.h
- tests/tests_api.c
- tests/tests_u2f_standard.c
- xpub API: send back a warning and do not echo if using a non-whitelisted keypath in order to match keypaths supported by the mobile app.
- Require reset before hardware wallet seed creation or recovery from backup. This matches what is already done in the desktop app.
- astyle styling for previous commits
> whitelist keypaths; require reset before reseeding

- src/u2f_device.c
- src/u2f_device.h
- tests/api.h
MyEtherWallet redid their website and put the old version of MEW at vintage.myetherwallet.com.
In addition, the 'hijack code' was changed from the U2F `challenge` parameter to the `appId` parameter, as the latter is a more stable representation of the website origin (for anti-phishing purposes). This was made apparent as the latest Chrome version changed how the `challenge` parameter was computed.
> update u2f hijack whitelist for vintage MEW and latest Chrome

- src/json.c
The stricter json generation changed the type of the error code from
number to string unintentionally. This changes it back.
> json: Change error code type to integer
