commander.h, utils.c
=> Remove unused includes

commander.c, memory.c, sd.c, sha2.c, tests_api.c, tests_openssl.c, tests_unit.c, utils.c, wallet.c
Will rebase when https://github.com/digitalbitbox/mcu/pull/3 gets merged.
=> Reduce variable scopes

CMakeLists.txt
I'll open more PRs to activate additional warning-flags that will need some code changes soon.
=> Warning flags

CMakeLists.txt, src/commander.c, src/flags.h, src/jsmn.c, src/led.c, src/memory.c, src/sham.c, tests/tests_cmdline.c
Please merge https://github.com/digitalbitbox/mcu/pull/13 first and I will rebase this one.
I've already made a PR just for Travis to check if building on clang is also good. Will install clang locally soon :)
Please check if the default switch options in the 'CMake: Add Wswitch-default flag' commit are good or if there is a better default.
=> Add more warnings: -Wmissing-declarations, Wswitch-default

src/ataes132.c, src/base58.c, src/base64.c, src/bip32.c, src/bip39_english.h, src/commander.c, src/flags.h, src/memory.c, src/random.c, src/random.h, src/sd.c, src/sd.h, src/sham.c, src/sham.h, src/utils.c, src/utils.h, src/wallet.c, src/wallet.h, tests/tests_unit.c
clear temporary buffers holding sensitive data
avoid memory leaks and seg faults for edge cases
add use of return flags
=> security fixes

README.md, src/random.c
Should work on Windows, but I can't test there atm.
=> Make TESTING random platform independent

src/random.c
Per an idea from Alex / Jonas, xor the output of the hardware random number generator with the user supplied hashed password, further removing trust needed for the hardware.
Reference: #28 
(the second commit will disappear on a rebase after merging #64)
=> Independent entropy to RNG

src/sd.c
Fixes #69 
Outputs a JSON array. For example:
```
{ "backup":  [
"verification.txt","autobackup_1.aes","backup.bak"
]
}
```
=> backup:list output JSON array

src/commander.c, src/flags.h, src/wallet.c, src/wallet.h, tests/tests_api.c
=> Update device API

src/firmware.c, src/random.c, src/random.h, src/startup.c, tests/tests_api.c
=> fix ssp canary asignment

src/commander.c, src/flags.h, tests/tests_api.c
Adds flexibility to be able to verify any data by 2FA. Needed for some multisig 2FA options.
=> add feature to AES encrypt blob using verify pw

Vagrantfile
=> vagrant build: get git version

tests/CMakeLists.txt, tests/tests_cmdline_live.c
Added: `tests/tests_cmdline_live.c`
=> send commands to a live device by command line

contrib/sign_firmware.py, src/bootloader.c, src/drivers/config/conf_usb.h, src/startup.c
- use short touch to enter bootloader; timeout to enter firmware
- remove touch requirement for erase command
EDIT - tested successfully on chip
=> update bootloader for UX

README.md, src/commander.c, src/drivers/common/components/memory/sd_mmc/sd_mmc.c, src/drivers/sam/drivers/uart/uart.c, src/drivers/sam/services/flash_efc/flash_efc.c, src/sd.c
Coverity offers static analysis for open source projects.
=> static analysis fixes and coverity badge

src/hmac.c, src/pbkdf2.c
=> clear memory in hmac

src/bootloader.c, src/bootloader.h, src/drivers/config/conf_usb.h, src/startup.c
(and some code cleaning)
useful during manufacturing
=> bootloader led blink command

src/commander.c, tests/tests_api.c
...instead of returning an error.
=> process non-sign commands if sign protocol interrupted

py/firmware_command.py, py/load_firware.py
firmware_command.py: python interface to send commands
load_firmware.py: python interface to bootloader for loading firmware
=> add python debug scripts

src/commander.c, src/flags.h
lock code hidden from UX with new smart verification setup. so make it longer for security.
=> longer lock code for tfa

src/sd.h
ref https://github.com/digitalbitbox/mcu/pull/151
Move the end text mark to the end of the text.
=> minor fix to pdf format

.travis.yml, CMakeLists.txt, README.md, Vagrantfile
Also switch to 64-bit linux in vagrant and print out compiler version during cmake build.
=> update to arm gcc 6.3.1 in vagrant and travis

src/u2f_device.h, tests/api.h
=> use macro constant for U2F_HIJACK_CODE size

src/commander.c
Purpose: faster quality control during manufacturing tests.
=> touch not required for relock bootloader or reset if not seeded

src/secp256k1.c, tests/tests_secp256k1.c
=> Update libsecp256k1 submodule

src/sd.c
=> bugfix DBB_ERR_SD_OPEN_DIR

py/dbb_utils.py
The bootloader v3.0 communication (composite device with HID iface instead of previous HID device) on Windows requires sending a series of 64-byte packets instead of a 4098-byte blob using the hidapi library.
=> bootloader USB comm (python test script) send 64-byte packets

src/u2f/u2f.h, src/u2f/u2f_hid.h, src/u2f_device.c
and packing U2F init response struct
=> zeroing struct before memcpy in U2F init

.travis.yml
travis does a shallow clone, and the reference commit was grafted (too
old). Move it to a more recent one.
=> ci: fix grafted commmit in shallow clone

.travis.yml, src/commander.c, src/flags.h, src/wallet.c, src/wallet.h, tests/tests_api.c
wallet.c/h: parse keypath into array of uint32_t values
tests_api.c: PIN exception should test presence of `recid`
=> signing code: validate change address

src/commander.c, src/wallet.c, src/wallet.h
Fixes Electrum multisig bug where our change keypath checking was too restrictive.
=> keypaths bugfix

.travis.yml, Dockerfile.dev, Makefile, README.md, Vagrantfile, py/README.md, src/commander.c
Update to the latest embedded compiler, and fix the new compiler warnings.
Updates the README and adds a convenience Makefile.
=> change to GCC ARM v8-2018-q4-major

src/led.c
3 times was too long for the U2F HID test
=> led.c: success 2 blinks instead of 3

src/led.c, src/touch.h
- updated function naming for better dev understanding
- blink off increased from 100ms to 200ms
- blink on remains at 100ms
- increased the overall pattern period from 3 sec to 4 sec
=> led.c: update blink timings for better comprehension

.travis.yml, Dockerfile.dev, Vagrantfile, dockerdev.sh, src/flags.h, src/touch.c, src/touch.h, src/u2f_device.c, tests/api.h, tests/tests_api.c
Fix some bugs introduced by windows 10 1903 update.
=> U2F mew fix

.travis.yml
An expired key fails validation of old commits.
7ff4854c7dcf3a8114e9a9a6030433bb03f2864a   Niklas Claesson   json: Change error code type to integer   Y
b432a5df5639ee20ecfc6e4a655036c6b5e0ef5b   Niklas Claesson   Add my signature   Y
=> update revision to start gpg sig checks from
